### PR TITLE
Support for Top Tagger SF

### PR DESCRIPTION
**Pull request by JHiltbrand**
Companion PR: https://github.com/StealthStop/Analyzer/pull/423

This PR adds functionality to `ScaleFactors` to calculate a final top tagger SF in the same we calculate the b tag SF.
Here we use the "method 1a" as used for the b tag SF, which incorporates efficiency and mistag rate.
The `ScaleFactors` module is now passed a top tagger histogram file that contains SF histos as well as overall efficiency and mistag rate histograms.

Attn: @semrat and @cmadrid1, if I understand how the b tag SF works, then we need to discuss how we do the same sort of thing for top tagger i.e. can we cut on the top discriminator _inside our framework_ and then count tops ? Rather than passing the working point to the top tagger module. I would like to discuss further.

### CODE REVIEW

**Comment by JHiltbrand** [comment]
> Hey @JHiltbrand this will be tough in general. Maybe we can use something like this: https://github.com/StealthStop/Framework/blob/master/Framework/include/RunTopTagger.h#L418-L419

Yeah, the reason I bring this up is that for calculating the final b tagger SF (via method 1a [1]) we loop over all b tag candidates in an event, including ones that do not pass our standard medium DeepFlavour working point. Thus, I would think we need to do the same with top tag candidates. However, right now, because we pass the top tagger WP to the top tagger, we are only left with candidates that necessarily pass the WP. In that case, I feel the final calculated top tagger SF for an event would be biased in some way (?) Maybe it does not matter, I am not entirely sure...

[1] https://github.com/StealthStop/Framework/blob/master/Framework/include/BTagCorrector.h#L262-L297

**Comment by JHiltbrand** [comment]
Hello @cmadrid1 and @semrat,

OK, so the annoying thing is that the `getTopCandidates()` function from the `TopTagger` framework does not return what we want. It gives candidates, but with literally no preselections on the constituents pt, their angular separation, combined mass etc. Which is not what we need. We need any candidate (discriminant between 0 and 1), but with all the pt, mass, angular selections applied.

Thus, to use the top tagger SF successfully in _our_ framework, we would need to pass a working point of 0.0 and just use the `getTops()` method. And then we would just have to apply the working point and cut on number of tops.

**Comment by JHiltbrand** [comment]
> Hello @cmadrid1 and @semrat,
> 
> OK, so the annoying thing is that the `getTopCandidates()` function from the `TopTagger` framework does not return what we want. It gives candidates, but with literally no preselections on the constituents pt, their angular separation, combined mass etc. Which is not what we need. We need any candidate (discriminant between 0 and 1), but with all the pt, mass, angular selections applied.
> 
> Thus, to use the top tagger SF successfully in _our_ framework, we would need to pass a working point of 0.0 at the config level and just use the `getTops()` method. And then we would just have to apply the working point and cut on number of tops.

Please see [d5d488d](https://github.com/StealthStop/Framework/pull/364/commits/d5d488de8a3ea519b7d912ae26ec9ab1827c84d8) and [1c9e8a7](https://github.com/StealthStop/Analyzer/pull/423/commits/1c9e8a7ef4c8e840d2227706495872e139791f5d) to do working point check inside of `RunTopTagger.h`

@semrat will make top tagger releases with the merged and resolved working points set to 0.

**Comment by semrat** [comment]
@JHiltbrand **I made the releases:**

https://github.com/susy2015/TopTaggerCfg/releases/tag/StealthStop_DeepFlavorWp0.2598_DeepResolvedwp0.00_DeepAK8wp0.00_2016preVFPUL

https://github.com/susy2015/TopTaggerCfg/releases/tag/StealthStop_DeepFlavorWp0.2489_DeepResolvedwp0.00_DeepAK8wp0.00_2016postVFPUL

https://github.com/susy2015/TopTaggerCfg/releases/tag/StealthStop_DeepFlavorWp0.3040_DeepResolvedwp0.00_DeepAK8wp0.00_2017UL

https://github.com/susy2015/TopTaggerCfg/releases/tag/StealthStop_DeepFlavorWp0.2783_DeepResolvedwp0.00_DeepAK8wp0.00_2018UL

If we need their link, I attached here !!!

**Comment by JHiltbrand** [comment]
> @JHiltbrand **I made the releases:**
> 
> https://github.com/susy2015/TopTaggerCfg/releases/tag/StealthStop_DeepFlavorWp0.2598_DeepResolvedwp0.00_DeepAK8wp0.00_2016preVFPUL
> 
> https://github.com/susy2015/TopTaggerCfg/releases/tag/StealthStop_DeepFlavorWp0.2489_DeepResolvedwp0.00_DeepAK8wp0.00_2016postVFPUL
> 
> https://github.com/susy2015/TopTaggerCfg/releases/tag/StealthStop_DeepFlavorWp0.3040_DeepResolvedwp0.00_DeepAK8wp0.00_2017UL
> 
> https://github.com/susy2015/TopTaggerCfg/releases/tag/StealthStop_DeepFlavorWp0.2783_DeepResolvedwp0.00_DeepAK8wp0.00_2018UL
> 
> If we need their link, I attached here !!!

Hello @semrat,
Excellent, I will test them out on my branch.

**Pull request merged**
